on:
  release:
    types: [published]

name: Upload PDF on release

jobs:
  build:
    name: Build and upload PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          make all
      - name: Upload Release Asset
        uses: JasonEtco/upload-to-release@d648f1babf77
        with:
          args: ./build/report.pdf application/pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
